### ISSUE TITLE
Bug: Extra zero exponents

### ISSUE THREAD

**Issue by nukisman** [csicar/purescript-typelevel-measures#1]
Hi @csicar ! 
There is a problem with measures of exp = 0
```
> voltage 6.0
6.0·A⁻¹kg¹m²s⁻³

> resistance 2.0
2.0·A⁻²kg¹m²s⁻³

> amperage 3.0
3.0·A¹

> voltage 6.0 // resistance 2.0  -- semantically equal to previous
3.0·A¹kg⁰m⁰s⁰
```
But this gives type error:
```
> (voltage 6.0 // resistance 2.0) == amperage 3.0
...
 Could not match type
                                                 
    ( kg :: MeasureExp KgT (Pos Z)               
    , meter :: MeasureExp MeterT (Pos Z)         
    , sec :: MeasureExp SecT (Pos Z)             
    , ampere :: MeasureExp AmpereT (Pos (Succ Z))
    )                                            
                                                 
  with type
                                                 
    ( ampere :: MeasureExp AmpereT (Pos (Succ Z))
    )    
...
```
I suppose zero exponents should be avoided during simplification.

**Comment by csicar** [comment]
Should be fixed in v0.3.2

**Comment by nukisman** [comment]
> Should be fixed in v0.3.2

@csicar v0.3.2 gives compilation error:
```
$ psc-package repl
Compiling Type.Data.Units
Error found:
in module Type.Data.Units
at .psc-package/local/typelevel-measures/v0.3.2/src/Units.purs:10:111 - 10:126 (line 10, column 111 - line 10, column 126)

  Cannot import type class IsZeroInt from module Type.Data.Peano.Int
  It either does not exist or the module does not export it.


See https://github.com/purescript/documentation/blob/master/errors/UnknownImport.md for more information,
or to contribute content related to this error.
```

**Comment by csicar** [comment]
IsZeroInt is a new class is `purescript-typelevel-peano` version `v0.1.6`. Could you double check, that your project / package-set requires that version?

**Comment by nukisman** [comment]
> IsZeroInt is a new class is `purescript-typelevel-peano` version `v0.1.6`. Could you double check, that your project / package-set requires that version?

Yes it works with `v0.1.6`! Thanks!
